from fastapi import HTTPException, status

from app.core.config import get_settings
from app.schemas.analysis import AnalysisCategory, AnalysisItem, AiAnalysis
from app.schemas.extraction import DocumentType, LabResultStatus, LabTest
from app.services.llm.base import LLMProvider

DISCLAIMER = (
    "This explanation is educational and generated by AI. It is not a diagnosis, "
    "does not replace professional medical advice, and never invents reference "
    "ranges. Always discuss your results with a qualified healthcare professional."
)


class StubProvider(LLMProvider):
    """Deterministic provider used for tests and keyless local development."""

    async def explain(
        self,
        document_type: DocumentType,
        raw_text: str,
        lab_tests: list[LabTest],
    ) -> AiAnalysis:
        items = [self._item_for(test) for test in lab_tests]
        concerns = [
            f"{test.name} ({test.value})"
            for test in lab_tests
            if test.status
            in (LabResultStatus.ABOVE_RANGE, LabResultStatus.BELOW_RANGE, LabResultStatus.POSITIVE)
        ]
        label = document_type.value.replace("_", " ")
        if lab_tests:
            summary = (
                f"Educational summary for {len(lab_tests)} test(s) extracted from "
                f"this {label} document."
            )
        else:
            summary = (
                f"Educational overview of this {label} document. "
                "No structured laboratory tests were extracted."
            )
        return AiAnalysis(
            summary=summary,
            disclaimer=DISCLAIMER,
            concerns=concerns,
            items=items,
        )

    @staticmethod
    def _item_for(test: LabTest) -> AnalysisItem:
        result = test.value
        if test.unit:
            result = f"{result} {test.unit}"
        if test.status == LabResultStatus.WITHIN_RANGE:
            return AnalysisItem(
                test_name=test.name,
                category=AnalysisCategory.REFERENCE_COMPARISON,
                explanation=(
                    f"{test.name} ({result}) is within the reference range"
                    + (f" ({test.reference_range})" if test.reference_range else "")
                    + ". This is an educational comparison; confirm with your clinician."
                ),
            )
        if test.status in (LabResultStatus.ABOVE_RANGE, LabResultStatus.BELOW_RANGE):
            direction = "above" if test.status == LabResultStatus.ABOVE_RANGE else "below"
            return AnalysisItem(
                test_name=test.name,
                category=AnalysisCategory.POSSIBLE_CONTEXT,
                explanation=(
                    f"{test.name} ({result}) falls {direction} the reference range"
                    + (f" ({test.reference_range})" if test.reference_range else "")
                    + ". Several possible contexts exist; this is not a diagnosis — "
                    "discuss it with your clinician."
                ),
            )
        if test.status in (LabResultStatus.POSITIVE, LabResultStatus.NEGATIVE):
            return AnalysisItem(
                test_name=test.name,
                category=AnalysisCategory.POSSIBLE_CONTEXT,
                explanation=(
                    f"{test.name} returned {result}. The meaning depends on context; "
                    "discuss it with your clinician."
                ),
            )
        return AnalysisItem(
            test_name=test.name,
            category=AnalysisCategory.EDUCATION,
            explanation=(
                f"{test.name}: the result is {result}. An automatic reference "
                "comparison could not be determined — ask your clinician."
            ),
        )


def get_llm_provider() -> LLMProvider:
    settings = get_settings()
    name = settings.llm_provider.strip().lower()
    if name in ("openai", "openrouter", "agentrouter"):
        if not settings.openai_api_key:
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="OpenAI provider not configured",
            )
        from app.services.llm.openai_provider import OpenAIProvider

        return OpenAIProvider(
            api_key=settings.openai_api_key,
            model=settings.openai_model,
            base_url=settings.openai_base_url,
        )
    return StubProvider()