<script setup lang="ts">
withDefaults(defineProps<{ text?: string }>(), {
  text: 'This explanation is educational and generated by AI. It is not a diagnosis and never replaces professional medical advice. Always discuss your results with a qualified healthcare professional.',
})
</script>

<template>
  <div class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">
    <strong>Important:</strong> {{ text }}
  </div>
</template>