<?php

namespace App\DTOs;

/**
 * The health-query outcome returned to the caller.
 *
 * `query_id` is generated by the backend and passed to the AI service so a query
 * can be traced internally without logging the user's health context.
 */
final class HealthQueryResultDto
{
    public function __construct(
        public readonly string $queryId,
        public readonly string $intent,
        public readonly HealthQueryResponseDto $answer,
    ) {}
}